"""
This type stub file was generated by pyright.
"""

import typing as t
import sqlalchemy as sa
import sqlalchemy.event as sa_event
import sqlalchemy.orm as sa_orm
from flask import current_app, has_app_context
from flask.signals import Namespace
from .session import Session

if t.TYPE_CHECKING:
    ...
_signals = ...
models_committed = ...
before_models_committed = ...
