"""
This type stub file was generated by pyright.
"""

import typing
from typing import Any, Callable, Dict, NoReturn, Optional, Tuple, Type, Union
from . import coercions, operators, roles, type_api
from .elements import BinaryExpression, ClauseElement, CollationClause, CollectionAggregate, ColumnElement, ExpressionClauseList, False_, Null, OperatorExpression, True_, UnaryExpression, and_, or_
from .operators import OperatorType, custom_op
from .. import exc, util
from .type_api import TypeEngine

"""Default implementation of SQL comparison operations."""
_T = typing.TypeVar("_T", bound=Any)
if typing.TYPE_CHECKING:
    ...
operator_lookup: Dict[str, Tuple[Callable[..., ColumnElement[Any]], util.immutabledict[str, Union[OperatorType, Callable[..., ColumnElement[Any]]]],],] = ...
