"""
This type stub file was generated by pyright.
"""

import json as _json
import typing as t

class _CompactJSON:
    """Wrapper around json module that strips whitespace."""
    @staticmethod
    def loads(payload: str | bytes) -> t.Any:
        ...
    
    @staticmethod
    def dumps(obj: t.Any, **kwargs: t.Any) -> str:
        ...
    


