"""
This type stub file was generated by pyright.
"""

def gensalt(rounds: int = ..., prefix: bytes = ...) -> bytes:
    ...

def hashpw(password: bytes, salt: bytes) -> bytes:
    ...

def checkpw(password: bytes, hashed_password: bytes) -> bool:
    ...

def kdf(password: bytes, salt: bytes, desired_key_bytes: int, rounds: int, ignore_few_rounds: bool = ...) -> bytes:
    ...

